# Generated by Django 2.2.13 on 2020-08-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0117_auto_20200804_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalsplan',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RemoveField(
            model_name='signalsplan',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='signalsplan',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='signalsplan',
            name='report_time',
        ),
        migrations.AddField(
            model_name='signalsplan',
            name='schedule',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='signalsplan',
            name='signal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='signals.Signal'),
        ),
    ]
