# Generated by Django 2.2.13 on 2020-08-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0118_auto_20200805_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_level_name1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_level_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_level_name3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_level_name4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
