# Generated by Django 2.2.13 on 2020-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0119_auto_20200807_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalsplan',
            old_name='emp',
            new_name='reporter',
        ),
        migrations.RemoveField(
            model_name='signalsplan',
            name='schedule',
        ),
        migrations.AddField(
            model_name='signalsplan',
            name='schedule_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
