# Generated by Django 2.2.13 on 2020-08-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0121_signal_finished_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='is_issue_finish_image',
            field=models.BooleanField(default=False),
        ),
    ]
