# Generated by Django 2.2.13 on 2020-08-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0122_attachment_is_issue_finish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orac_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('oracCode', models.CharField(max_length=100)),
                ('oracCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('oracType', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CityObjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_object_assignments', to='signals.Signal')),
                ('city_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_object_assignments', to='signals.CityObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='city_object',
            field=models.ManyToManyField(blank=True, through='signals.CityObjectAssignment', to='signals.CityObject'),
        ),
    ]
