# Generated by Django 2.2.13 on 2020-08-25 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0123_auto_20200823_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCityObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complainID', models.CharField(max_length=200)),
                ('complainIDall', models.CharField(blank=True, max_length=200, null=True)),
                ('reportCount', models.CharField(max_length=200)),
                ('is_Orac', models.BooleanField(default=False)),
                ('city_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.CityObject')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.Signal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
