# Generated by Django 2.2.13 on 2020-08-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0125_auto_20200827_0702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'managed': True},
        ),
    ]
