# Generated by Django 2.2.13 on 2020-08-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0126_auto_20200827_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'managed': False},
        ),
    ]
