# Generated by Django 2.2.13 on 2020-08-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0127_auto_20200827_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
