# Generated by Django 2.2.13 on 2020-09-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0128_category_filter_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seda_signal_id', models.CharField(max_length=255)),
                ('mb_signal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facilitator_signal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mcc_signal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('web_form_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='state',
            field=models.CharField(blank=True, choices=[('m', 'Gemeld'), ('i', 'In afwachting van behandeling'), ('b', 'In behandeling'), ('h', 'On hold'), ('ingepland', 'Ingepland'), ('ready to send', 'Te verzenden naar extern systeem'), ('o', 'Afgehandeld'), ('a', 'Geannuleerd'), ('reopened', 'Heropend'), ('s', 'Gesplitst'), ('closure requested', 'Verzoek tot afhandeling'), ('split', 'split'), ('mig', 'mig'), ('sent', 'Verzonden naar extern systeem'), ('send failed', 'Verzending naar extern systeem mislukt'), ('done external', 'Melding is afgehandeld in extern systeem'), ('reopen requested', 'Verzoek tot heropenen')], default='m', help_text='Melding status', max_length=20),
        ),
        migrations.AlterField(
            model_name='statusmessagetemplate',
            name='state',
            field=models.CharField(choices=[('m', 'Gemeld'), ('i', 'In afwachting van behandeling'), ('b', 'In behandeling'), ('h', 'On hold'), ('ingepland', 'Ingepland'), ('ready to send', 'Te verzenden naar extern systeem'), ('o', 'Afgehandeld'), ('a', 'Geannuleerd'), ('reopened', 'Heropend'), ('s', 'Gesplitst'), ('closure requested', 'Verzoek tot afhandeling'), ('split', 'split'), ('mig', 'mig'), ('sent', 'Verzonden naar extern systeem'), ('send failed', 'Verzending naar extern systeem mislukt'), ('done external', 'Melding is afgehandeld in extern systeem'), ('reopen requested', 'Verzoek tot heropenen')], max_length=20),
        ),
    ]
