# Generated by Django 2.2.13 on 2020-10-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0130_department_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='id_mapping',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mapping', to='signals.IDMapping'),
        ),
        migrations.AddField(
            model_name='signal',
            name='schedule_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
