# Generated by Django 2.2.13 on 2020-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0131_auto_20201004_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='id_mapping',
        ),
        migrations.AddField(
            model_name='signal',
            name='facilitator_report_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='mb_report_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='webform_kenmark',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
