# Generated by Django 2.2.13 on 2020-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0133_auto_20201005_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='plan_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
