# Generated by Django 2.2.13 on 2020-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0134_auto_20201005_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalPlanUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_id', models.CharField(max_length=255)),
                ('assign_to', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='attachments/%Y/%m/%d/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='signal',
            name='updates',
            field=models.ManyToManyField(blank=True, to='signals.SignalPlanUpdate'),
        ),
    ]
