# Generated by Django 2.2.13 on 2020-10-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0136_district_neighbourhood_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='stadsdeel',
            field=models.CharField(choices=[('Centrum', 'Centrum'), ('B', 'Westpoort'), ('E', 'West'), ('M', 'Oost'), ('N', 'Noord'), ('T', 'Zuidoost'), ('K', 'Zuid'), ('F', 'Nieuw-West'), ('H', 'Het Amsterdamse Bos'), ('W', 'Weesp'), ('Loosduinen', 'Loosduinen'), ('Escamp', 'Escamp'), ('Segbroek', 'Segbroek'), ('Scheveningen', 'Scheveningen'), ('Centrum', 'Centrum'), ('Laak', 'Laak'), ('Haagse hout', 'Haagse hout'), ('Leidschenveen-Ypenburg', 'Leidschenveen-Ypenburg')], max_length=30, null=True),
        ),
    ]
