# Generated by Django 2.2.13 on 2020-10-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0137_auto_20201012_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='idmapping',
            name='issue_final_image',
            field=models.FileField(default=None, max_length=255, upload_to='attachments/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
