# Generated by Django 2.2.13 on 2020-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0138_idmapping_issue_final_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idmapping',
            name='issue_final_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='idmapping',
            name='seda_signal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
