# Generated by Django 2.2.13 on 2020-10-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0139_auto_20201018_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
