# Generated by Django 2.2.13 on 2020-10-29 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0142_auto_20201029_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.District'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='descriptionId',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
