# Generated by Django 2.2.13 on 2020-07-19 19:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horecacsvexport',
            options={'ordering': ('-isoyear', '-isoweek', '-created_at')},
        ),
        migrations.AlterField(
            model_name='horecacsvexport',
            name='uploaded_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=None), upload_to='exports/%Y'),
        ),
    ]
