# Generated by Django 2.2.13 on 2020-08-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200805_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
