# Generated by Django 2.2.13 on 2020-10-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0136_district_neighbourhood_postcode'),
        ('users', '0008_profile__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.District'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fac_district_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fac_neighbourhood_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fac_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facilitator_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
