# Generated by Django 2.2.13 on 2020-10-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201012_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mb_district_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mb_neighbourhood_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mb_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
